import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LandingLayout from "./context";
import Providers from "./progressbar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <LandingLayout>{children}</LandingLayout>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
